version: "3"
services:
  web:
    image: blarry/multitask:v1.0
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:

# Set proxy server, replace host:port with values for your servers
#ENV http_proxy "34.237.142.196":80
